### ISSUE TITLE
API has changed

### ISSUE THREAD

**Issue by andeersg** [Knutakir/btc-value#17]
It now requires an API key to work: https://pro.coinmarketcap.com/migrate/

**Comment by Knutakir** [comment]
Thanks! Will look into how to include a key to the module.

**Comment by Knutakir** [comment]
@andeersg this should now be fixed and pushed to npm.

**Comment by andeersg** [comment]
Awesome, I will test it 👍

**Comment by tmlee** [comment]
You might also want to consider the CoinGecko API https://www.coingecko.com/en/api
It is free and easy to use. No keys required and very flexible

**Comment by Knutakir** [comment]
@tmlee thanks for the suggestion! I will look into this. Might not replace the current one, but let the user choose between different providers. So I will create an issue for this later.
